// Projections: the board (Markdown for humans) and the evidence summary (JSON
// for machines) are GENERATED from graph + lock + probe. They are never edited
// by hand, so they cannot drift from the tests — the failure mode that produced
// 49 documentation-reconciliation commits out of 51.
//
// The run ledger is local, append-only and hash-chained (.local/, never
// committed): raw observations stay on the machine, sanitized summaries are
// committed. Harvested from the baseline's D-430/D-431 ledger discipline.
import { appendFileSync, existsSync, mkdirSync, readFileSync } from "node:fs";
import { dirname } from "node:path";
import { digest, short } from "./canonical.ts";
import type { Lock } from "./lock.ts";
import type { ProbeResult } from "./probe.ts";
import type { RatchetSpec } from "./spec.ts";
import type { TaskView } from "./state.ts";
import { rankFrontier, summarize } from "./state.ts";
import type { TaskGraph } from "./taskgraph.ts";

export interface BaselineRun { id: string; argv: string[]; exitCode: number; pass: number | null; fail: number | null; expects: number | null; tests: number | null }

export function renderBoard(spec: RatchetSpec, graph: TaskGraph, views: TaskView[], probe: ProbeResult | null, lock: Lock, orphans: string[]): string {
  const s = summarize(views);
  const L: string[] = [];
  L.push(`# ${spec.title} — task board`);
  L.push("");
  L.push("> GENERATED by `bun run ratchet board` from the task graph, the ratchet lock and the latest probe. Do not edit by hand; edit tests, code, or the source task list and regenerate.");
  L.push(`> Evidence class of every gate: **${spec.evidenceClass}**. Nothing on this board is live Provider/Account/browser evidence.`);
  L.push("> Green here is not completion: this board is a projection of the ratchet, which is authoritative only for computed D1 task/gate state. Raw truth: `bun run ratchet probe`. See `.project/ratchet/DESIGN.md` §Authority.");
  L.push("");
  L.push(`Source task list: \`${graph.source.path}\` (${short(graph.source.digest)}) · probe: ${probe ? `HEAD \`${probe.head}\`, Bun ${probe.bun}, ${probe.platform}, ${probe.totals.pass}/${probe.totals.gates} gates green, digest ${short(probe.digest)}` : "none (run `bun run ratchet probe`)"} · promoted gates: ${Object.keys(lock.promoted).length}`);
  L.push("");
  L.push(`| DONE | PROVEN | OPEN | CLAIMED | BLOCKED | REGRESSED | SUPERSEDED | total | frontier | missing proof |`);
  L.push(`| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |`);
  L.push(`| ${s.DONE} | ${s.PROVEN} | ${s.OPEN} | ${s.CLAIMED} | ${s.BLOCKED} | ${s.REGRESSED} | ${s.SUPERSEDED} | ${s.total} | ${s.frontier} | ${s.missingProof} |`);
  L.push("");
  const regressed = views.filter((v) => v.state === "REGRESSED");
  if (regressed.length) {
    L.push("## Regressions (fix before anything else)");
    L.push("");
    for (const v of regressed) L.push(`- **${v.id}** ${v.notes.filter((n) => n.startsWith("REGRESSED")).join("; ")}`);
    L.push("");
  }
  if (probe?.silentFiles.length) {
    L.push("## Gate files that produced no tests (load errors?)");
    L.push("");
    for (const f of probe.silentFiles) L.push(`- \`${f}\``);
    L.push("");
  }
  if (orphans.length) {
    L.push("## Orphan gates (task id not in the task list)");
    L.push("");
    for (const o of orphans) L.push(`- \`${o}\``);
    L.push("");
  }
  L.push("## Frontier (ranked by critical path, then tasks unblocked)");
  L.push("");
  const frontier = rankFrontier(views);
  if (!frontier.length) L.push("_empty_");
  for (const v of frontier) L.push(`- **${v.id}** ${v.outcome} — crit ${v.criticality}, unblocks ${v.unblocks}; \`bun run ratchet packet ${v.id}\``);
  L.push("");
  L.push("## All tasks");
  let phase = "";
  for (const v of views) {
    if (v.phase !== phase) {
      phase = v.phase;
      const t = graph.tasks.find((x) => x.id === v.id)!;
      L.push("");
      L.push(`### Phase ${phase} — ${t.phaseTitle}`);
      L.push("");
      L.push("| ID | State | Gates green/total | Outcome | Notes |");
      L.push("| --- | --- | --- | --- | --- |");
    }
    const green = v.gates.filter((g) => g.observed === "pass").length;
    const proofs = v.missingProof ? "—" : `${green}/${v.gates.length}${v.artifacts.length ? ` + ${v.artifacts.filter((a) => a.ok).length}/${v.artifacts.length} art.` : ""}`;
    const claim = v.claim ? ` · claimed by ${v.claim.by} until ${v.claim.expires}` : "";
    L.push(`| ${v.id} | ${v.state}${v.frontier ? " ★" : ""} | ${proofs} | ${esc(v.outcome)} | ${esc(v.notes.join("; "))}${claim} |`);
  }
  L.push("");
  return L.join("\n");
}

function esc(s: string): string {
  return s.replaceAll("|", "\\|");
}

export function buildEvidence(spec: RatchetSpec, graph: TaskGraph, views: TaskView[], probe: ProbeResult | null, lock: Lock, baseline: BaselineRun[] | undefined, previous: unknown): Record<string, unknown> {
  const prevBaseline = (previous as { baseline?: unknown } | null)?.baseline;
  const body = {
    schema: "ratchet.evidence/0",
    spec: spec.id,
    title: spec.title,
    evidenceClass: spec.evidenceClass,
    banner: spec.evidenceClass === "SIMULATED"
      ? "SIMULATED — every gate in this summary runs against synthetic, source-labelled fixtures and virtual realizations. No live Provider, Account, browser or model evidence is claimed."
      : `${spec.evidenceClass} evidence only.`,
    taskSource: graph.source,
    probe: probe ? { head: probe.head, bun: probe.bun, platform: probe.platform, totals: probe.totals, digest: probe.digest, silentFiles: probe.silentFiles } : null,
    summary: summarize(views),
    tasks: views.map((v) => ({
      id: v.id,
      state: v.state,
      gates: v.gates.map((g) => ({ key: g.key, observed: g.observed, promoted: g.promoted, specChanged: g.specChanged })),
      artifacts: v.artifacts.map((a) => ({ path: a.proof.path, ok: a.ok })),
      missingProof: v.missingProof,
      review: lock.reviews[v.id]?.at(-1) ?? null,
    })),
    baseline: baseline ?? prevBaseline ?? null,
    /** Present only when every gate passed in the latest probe and no gate file was silent. */
    semanticGate: probe && probe.totals.gates > 0 && probe.totals.fail === 0 && probe.totals.skip === 0 && probe.silentFiles.length === 0
      ? { head: probe.head, gates: probe.totals.gates, digest: probe.digest } : null,
    /** Present only when every recorded baseline command exited 0. */
    baselineGreen: (() => {
      const b = (baseline ?? prevBaseline) as BaselineRun[] | null | undefined;
      return Array.isArray(b) && b.length > 0 && b.every((r) => r.exitCode === 0) ? b.map((r) => `${r.id} ${r.pass}/${r.fail}`).join("; ") : null;
    })(),
    completion: lock.completion,
    /** C4: the four readings of "green" kept apart so no artifact collapses them. */
    interpretation: {
      ratchetModeGreen: "the ratchet-mode gate suite (`bun run d1:gates`) exits green while open gates run as expected failures — it means open gaps are represented honestly and promoted gates have not regressed, NOT that the deliverable works",
      probeTruth: probe ? { green: probe.totals.pass, red: probe.totals.fail, skipped: probe.totals.skip, total: probe.totals.gates } : null,
      semanticCompletion: !!(probe && probe.totals.gates > 0 && probe.totals.fail === 0 && probe.totals.skip === 0 && probe.silentFiles.length === 0),
      reviewedCompletion: lock.completion ? { head: lock.completion.head, at: lock.completion.at, by: lock.completion.by } : null,
    },
    limitations: [
      "Gate results are claims about the code at the probed HEAD only.",
      "A PROVEN task has promoted green gates but no independent review yet.",
      "Fixture and simulated results are never live results.",
      "Reviewer identity (`--by <label>`) is an auditable coordination label, not cryptographic proof that two labels are independent underlying actors; the engine enforces label separation, not actor independence (C2).",
      "Ratchet-mode green (`d1:gates`) is not completion; only the probe-green frontier plus independent reviews, and finally the completion record, are (C4).",
    ],
  };
  return { ...body, digest: digest(body) };
}

/** Parse Bun's summary lines: " 62 pass", " 0 fail", " 1622 expect() calls", "Ran 62 tests". */
export function parseBunSummary(output: string): Pick<BaselineRun, "pass" | "fail" | "expects" | "tests"> {
  const num = (re: RegExp) => { const m = re.exec(output); return m ? Number(m[1]) : null; };
  return {
    pass: num(/^\s*(\d+) pass\s*$/m),
    fail: num(/^\s*(\d+) fail\s*$/m),
    expects: num(/^\s*(\d+) expect\(\) calls\s*$/m),
    tests: num(/^Ran (\d+) tests?/m),
  };
}

export interface LedgerEntry { seq: number; prev: string | null; kind: string; at: string; head: string; data: unknown; digest: string }

export function appendLedger(path: string, kind: string, head: string, data: unknown, now = new Date()): LedgerEntry {
  mkdirSync(dirname(path), { recursive: true });
  const entries = readLedger(path);
  const last = entries.at(-1);
  const core = { seq: (last?.seq ?? 0) + 1, prev: last?.digest ?? null, kind, at: now.toISOString(), head, data };
  const entry: LedgerEntry = { ...core, digest: digest(core) };
  appendFileSync(path, JSON.stringify(entry) + "\n");
  return entry;
}

export function readLedger(path: string): LedgerEntry[] {
  if (!existsSync(path)) return [];
  return readFileSync(path, "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l) as LedgerEntry);
}

export function verifyLedger(entries: LedgerEntry[]): { ok: boolean; badAt?: number } {
  let prev: string | null = null;
  for (const e of entries) {
    const { digest: d, ...core } = e;
    if (e.prev !== prev || digest(core) !== d) return { ok: false, badAt: e.seq };
    prev = d;
  }
  return { ok: true };
}
